### ISSUE TITLE
Prefer configuring project path via environment variables over buildpack.yml

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/dotnet-execute#151]
## Summary
The current implementation allows a buildpack user to configure a project path using a `buildpack.yml` configuration file with the following contents:

```yaml
dotnet-build:
  project-path: ./src/asp_web_app
```

After the approval of [RFC0002](https://github.com/paketo-buildpacks/dotnet-core/blob/main/rfcs/0002-buildpack-yml-to-env-var.md) we should be preferring to allow that configuration via an environment variable like:

```shell
BP_DOTNET_PROJECT_PATH=./src/asp_web_app
```

### Deprecation Notice
The buildpack should emit a deprecation notice via log output when a `buildpack.yml` file appears in the application source code with configuration for this buildpack. The deprecation notice should appear similar to notices that have been implemented in [other](https://github.com/paketo-buildpacks/mri/blob/4e486427aa4ca316016403686ca1755cab9f554c/build.go#L68-L73) [buildpacks](https://github.com/paketo-buildpacks/go-dist/blob/de73c417686ab36e7686d881e2d0c769939f8ea5/build.go#L53-L58).

**Comment by sophiewigmore** [comment]
The `dotnet-build` section of the `buildpack.yml` has overlap with `dotnet-publish`. Should both this buildpack and `dotnet-publish` emit the same warning about using the buildpack.yml? It would clutter the logs with repeated information in the cases where both buildpacks are used.

**Comment by kvedurmu** [comment]
Supporting an environment variable for this (along with https://github.com/paketo-buildpacks/dotnet-publish/issues/154) would make it easier for users to build .NET Core apps with multiple projects . Currently, to specify a project path, users will have to make a code change to buildpack.yml to change the project path.

**Comment by thangchung** [comment]
That's cool.

I have a quick question that if I have 2 .NET Core projects and shared the same contract DTOs (such as Blazored Client and Server-side, or Microservices with the shared building blocks), and could I use `gcr.io/paketo-buildpacks/dotnet-core` to build these kinds of projects? I struggle to make it work, but no luck, look like the `buildpacks only scan and check all dependencies inside the folder it belongs to (if I reference into another project folder, not in this project, that mean, it's outside of the current project folder then it wasn't working and couldn't make the build succeed)

**Comment by ryanmoran** [comment]
Hi @thangchung. I think I understand the scenario you are describing, but could you provide some more concrete details, like maybe an example repo and configuration you are using to run the buildpack?

**Comment by thangchung** [comment]
Hih @ryanmoran. I have the demo repo at https://github.com/thangchung/practical-dotnet-with-cna

In this repo, I have the shared library with named [`shared/WeatherLib`](https://github.com/thangchung/practical-dotnet-with-cna/tree/main/shared/WeatherLib), and the API with named [`service1`](https://github.com/thangchung/practical-dotnet-with-cna/tree/main/service1) which referenced to `shared/WeatherLib`

I tried to build `service1` as

```bash
$ pack build webapi --buildpack gcr.io/paketo-buildpacks/dotnet-core
```

But I have got the error message that the `service1` couldn't find the `shared/WeatherLib`

Hope this description will make you clear about what I have struggled with.
