### ISSUE TITLE
App goes in infinate restart loop if it creates any files while BP_LIVE_RELOAD_ENABLED=true

### ISSUE THREAD

**Issue by macsux** [paketo-buildpacks/dotnet-execute#258]
## What happened?
If Live reload is enabled via BP_LIVE_RELOAD_ENABLED=true and the application creates any files in it's work dir, the process is restarted immediately. An example of this is an app that uses SQLite as a local cache store, but the creation and manipulation of temporary files in applications work dir is very common as well.

* What were you attempting to do?
Create a .NET core app docker image via buildpack with hot reload enabled

* What did you expect to happen?
App starts up fine and restarts only if one of the original files that went into container is modified

* What was the actual behavior? Please provide log output, if possible.
App restarts on change to ANY file in it's working directory, including those caused by the app itself

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
pack 0.22.0+git-26d8c5c.build-2970

* What buildpacks are you using? Please include versions.
```
paketo-buildpacks/ca-certificates     2.4.2
paketo-buildpacks/dotnet-core-runtime 0.2.2
paketo-buildpacks/dotnet-core-aspnet  0.2.2
paketo-buildpacks/dotnet-core-sdk     0.2.1
paketo-buildpacks/icu                 0.0.102
paketo-buildpacks/dotnet-publish      0.3.1
paketo-buildpacks/dotnet-execute      0.5.1
```
* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
paketobuildpacks/run:full-cnb

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

https://github.com/macsux/dotnet-accelerator
The app in question is able to work off SQLite which it creates in current working directory. This feature has been traced to infinite restart loop when hot reload is enabled by the buildpack.

**Comment by ForestEckhardt** [comment]
Thanks for bring this up @macsux. Out of curiosity is the location of files that are generated known at build time? If that is the case would the addition of some sort of environment variable like `BP_IGNORE_FILE_WATCH` (name definitely subject to change) solve this issue?

**Comment by macsux** [comment]
In my case it was a locally created sqlite db and config file changes which i didn't want restarting the app. Watchexec allows ignore argument to be specified multiple times and supports patterns. If you're going to expose it as env var, it needs to be able to support multiple patterns via some kinda delimiter like `;`

**Comment by ForestEckhardt** [comment]
@macsux After doing a little bit of reading up on the `watchexe` CLI I discovered that is should respect a `.gitignore` or a `.ignore` file and it will not monitor those files for restarts. Here is the [feature list](https://github.com/watchexec/watchexec/tree/main/cli#features) that outlines this functionality. Would you be willing to give this a try and see if it works for you and then we can potentially discuss further options?

**Comment by fg-j** [comment]
For now, I'm going to close this since `.gitignore` and `.ignore` provide workarounds for the problem. Feel free to reopen if this continues to be a blocking issue for you.
