### ISSUE TITLE
Use ASP.NET mechanism to to specify the port

### ISSUE THREAD

**Issue by joshuatcasey** [paketo-buildpacks/dotnet-execute#282]
Currently we use environment variable `PORT` to override the port. I propose not using a bespoke variable and instead relying on .NET env variable such as `ASPNETCORE_URLS`. This should mean we no longer need the `PORT` env variable, although it may be preferable to maintain both right now [code](https://github.com/paketo-buildpacks/dotnet-execute/blob/08f965dd6adac9154cf3f0406152402ca3d9f9c0/build.go#L36).

[ASPNETCORE_URLS](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0)

Blocks #273. Note that interpolating an environment variable such as `${PORT:-8080}` will not be supported with direct processes.

**Comment by fg-j** [comment]
+1 to maintaining both until/unless we get a clear signal that people aren't relying on `PORT`.

**Comment by joshuatcasey** [comment]
We can close this issue. #277 solves this by introducing an `exec.d` script to inspect both `ASPNETCORE_URLS` and `PORT` and set the port accordingly.
